version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
 build:
   executor: android/android

   steps:
     - checkout
     - run:
         command: ./gradlew build
     - run:
	 name: Install fastlane
         command: bundle install
     - run:
	 name: Execute fastlane
	 command: bundle exec fastlane playstore
